/* gipsyc.h

        Copyright (c) Kapteyn Laboratorium Groningen 1990
        All Rights Reserved.

#>            gipsyc.dc3

Header:       gipsyc

Purpose:      This include file should be included in all C sources
              of GIPSY level one, two and three routines.

File:         gipsyc.h

Author:       K.G. Begeman

Use:          #include "gipsyc.h"

Description:  The include file defines the ANSI-F77 types for the
              Fortran to C interface:
              Fortran               C         C
              character             fchar     character
              integer               fint      integer
              logical               bool      logical
              real                  float     real
              double precision      double    double precision
              complex               complex   complex

              Furthermore the macros tobool(l) and toflog(l) are defined.
              tobool(l) converts a Fortran logical to a C true or false value
              and toflog(l) converts a C true or false value to a Fortran
              logical which is .TRUE. or .FALSE. resp.

              Also some simple GIPSY programming utilities are defined, like:
                      char2str
                      str2char
                      tofchar
                      zadd

Updates:      Sep 21, 1988: KGB, Document created.
              Sep 20, 1989: JPT, Fortran equivalent types included.
              Feb 13, 1990: KGB, Definition of GIPSY C utilities included.

#<

*/

#if     !defined(_GIPSYC_H)
#define _GIPSYC_H

#include	"osdef.h"	/* get __'machine'__ */
#include        "f2cvvdefs.h"   /* system dependent file (generated by f2cvv) */

#define integer         fint    /* 'Fortran' integer equivalent */
#define logical         bool    /* 'Fortran' logical equivalent */
#define real            float   /* 'Fortran' real equivalent */
#define character       fchar   /* 'Fortran' character equivalent */
#define precision               /* 'Fortran' double precision equivalent */

extern  int     char2str(fchar fc,char *cc,int len);
extern  int     str2char(char *cc,fchar fc);
extern  fchar   tofchar (char *cc);
extern	char	*zadd(fchar fc);

#endif
