/* pgplot.h */
#if !defined(_pgplot_h_)
#define _pgplot_h_
extern bool ggixor_c(bool *);
extern void pgarro_c(float *,float *,float *,float *);
extern void pgask_c(bool *);
extern void pgaxis_c(fchar,float *,float *,float *,float *,float *,float *,float *,fint *,float *,float *,float *,float *,float *);
extern fint pgband_c(fint *,fint *,float *,float *,float *,float *,fchar);
extern void pgbbuf_c(void);
extern fint pgbeg_c(fint *,fchar,fint *,fint *);
extern void pgbin_c(fint *,float *,float *,bool *);
extern void pgbox_c(fchar,float *,fint *,fchar,float *,fint *);
extern void pgcirc_c(float *,float *,float *);
extern void pgclos_c(void);
extern void pgconb_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,fint *,float *,float *);
extern void pgconf_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,float *,float *);
extern void pgconl_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,float *,fchar,fint *,fint *);
extern void pgcons_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,fint *,float *);
extern void pgcont_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,fint *,float *);
extern void pgcotic_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,fint *,float *,float *,float *,fint *);
extern void pgctab_c(float *,float *,float *,float *,fint *,float *,float *);
extern fint pgcurs_c(float *,float *,fchar);
extern void pgdraw_c(float *,float *);
extern void pgebuf_c(void);
extern void pgend_c(void);
extern void pgenv_c(float *,float *,float *,float *,fint *,fint *);
extern void pgeras_c(void);
extern void pgerr1_c(fint *,float *,float *,float *,float *);
extern void pgerrb_c(fint *,fint *,float *,float *,float *,float *);
extern void pgerrx_c(fint *,float *,float *,float *,float *);
extern void pgerry_c(fint *,float *,float *,float *,float *);
extern void pgetxt_c(void);
extern fint pgexist_c(fint *);
extern void pggray_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,float *,float *);
extern void pghi2d_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,fint *,float *,bool *,float *);
extern void pghist_c(fint *,float *,float *,float *,fint *,fint *);
extern void pgiden_c(void);
extern void pgimag_c(float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,float *,float *);
extern void pglab_c(fchar,fchar,fchar);
extern void pglcur_c(fint *,fint *,float *,float *);
extern void pgldev_c(void);
extern void pglen_c(fint *,fchar,float *,float *);
extern void pgline_c(fint *,float *,float *);
extern void pgmove_c(float *,float *);
extern void pgmtxt_c(fchar,float *,float *,float *,fchar);
extern void pgncur_c(fint *,fint *,float *,float *,fint *);
extern void pgnumb_c(fint *,fint *,fint *,fchar,fint *);
extern void pgolin_c(fint *,fint *,float *,float *,fint *);
extern fint pgopen_c(fchar);
extern void pgpage_c(void);
extern void pgpanl_c(fint *,fint *);
extern void pgpap_c(float *,float *);
extern void pgpat_c(float *);
extern void pgpixl_c(fint *,fint *,fint *,fint *,fint *,fint *,fint *,float *,float *,float *,float *);
extern void pgpnts_c(fint *,float *,float *,fint *,fint *);
extern void pgpoly_c(fint *,float *,float *);
extern void pgpt_c(fint *,float *,float *,fint *);
extern void pgpt1_c(float *,float *,fint *);
extern void pgptxt_c(float *,float *,float *,float *,fchar);
extern void pgqah_c(fint *,float *,float *);
extern void pgqbci_c(fint *);
extern void pgqcf_c(fint *);
extern void pgqch_c(float *);
extern void pgqci_c(fint *);
extern void pgqcir_c(fint *,fint *);
extern void pgqclp_c(fint *);
extern void pgqcol_c(fint *,fint *);
extern void pgqcr_c(fint *,float *,float *,float *);
extern void pgqcs_c(fint *,float *,float *);
extern void pgqdt_c(fint *,fchar,fint *,fchar,fint *,fint *);
extern void pgqfs_c(fint *);
extern void pgqhs_c(float *,float *,float*);
extern void pgqid_c(fint *);
extern void pgqimi_c(fint *);
extern void pgqinf_c(fchar,fchar,fint *);
extern void pgqitf_c(fint *);
extern void pgqls_c(fint *);
extern void pgqlw_c(fint *);
extern void pgqndt_c(fint *);
extern void pgqpos_c(float *,float *);
extern void pgqtbg_c(fint *);
extern void pgqtxt_c(float *,float *,float *,float *,fchar,float *,float *);
extern void pgqvp_c(fint *,float *,float *,float *,float *);
extern void pgqvsz_c(fint *,float *,float *,float *,float *);
extern void pgqwin_c(float *,float *,float *,float *);
extern void pgrect_c(float *,float *,float *,float *);
extern float pgrnd_c(float *,fint *);
extern void pgrnge_c(float *,float *,float *,float *);
extern void pgsah_c(fint *,float *,float *);
extern void pgsave_c(void);
extern void pgsbci_c(fint *);
extern void pgscf_c(fint *);
extern void pgsch_c(float *);
extern void pgsci_c(fint *);
extern void pgscir_c(fint *,fint *);
extern void pgsclp_c(fint *);
extern void pgscr_c(fint *,float *,float *,float *);
extern void pgscrl_c(float *,float *);
extern void pgscrn_c(fint *,fchar,fint *);
extern void pgsfs_c(fint *);
extern void pgshls_c(fint *,float *,float *,float *);
extern void pgshs_c(float *,float *,float *);
extern void pgsimi_c(fint *);
extern void pgsitf_c(fint *);
extern void pgslct_c(fint *);
extern void pgsls_c(fint *);
extern void pgslw_c(fint *);
extern void pgsncr_c(fint *,float *,float *,float *,fint *);
extern void pgstbg_c(fint *);
extern void pgsubp_c(fint *,fint *);
extern void pgsvp_c(float *,float *,float *,float *);
extern void pgswin_c(float *,float *,float *,float *);
extern void pgtbox_c(fchar,float *,fint *,fchar,float *,fint *);
extern void pgtext_c(float *,float *,fchar);
extern void pgtick_c(float *,float *,float *,float *,float *,float *,float *,float *,float *,fchar);
extern void pgunsa_c(void);
extern void pgupdt_c(void);
extern void pgvect_c(float *,float *,fint *,fint *,fint *,fint *,fint *,fint *,float *,fint *,float *,float *);
extern void pgvsiz_c(float *,float *,float *,float *);
extern void pgvstd_c(void);
extern void pgwedg_c(fchar,float *,float *,float *,float *,fchar);
extern void pgwnad_c(float *,float *,float *,float *);
#endif
